package com.gsim.task;

/**
 * 任务类型枚举。
 */
public enum TaskType {
    RUN_TURN,
    ANALYZE_PLAYER_ACTIONS,
    GENERATE_CAMPAIGN_REPORT,
    GENERATE_NEWS_POST,
    UPDATE_TIMELINE,
    UPDATE_WORLD_STATE,
    RESEARCH_TOPIC,
    ADJUDICATE_ACTION,
    GENERATE_NARRATIVE,
    SUMMARIZE_TURN,
    IMPORT_DOCUMENTS,
    SEARCH_DATABASE,
    UNKNOWN
}
